### ISSUE TITLE
ERR_HTTP_HEADERS_SENT error message causing issues with rendering the images

### ISSUE THREAD

**Issue by sam-grierson** [sam-grierson/Group-Project#25]
Theres a persitant problem with the renders where on the error handling it doesnt like re-rendering some of the pages and it cause the images to not show properly. It throws an error to the console but the website still functions correctly as far as I can see.

This is the error message im getting:

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client 
at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (F:\Uni\group-proj\research\Group-Project\node_modules\express\lib\response.js:771:10) at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (F:\Uni\group-proj\research\Group-Project\node_modules\express\lib\response.js:771:10)
    at done (F:\Uni\group-proj\research\Group-Project\node_modules\express\lib\response.js:1008:10)
    at tryHandleCache (F:\Uni\group-proj\research\Group-Project\node_modules\ejs\lib\ejs.js:260:5)
    at View.exports.renderFile [as engine] (F:\Uni\group-proj\research\Group-Project\node_modules\ejs\lib\ejs.js:459:10)
    at View.render (F:\Uni\group-proj\research\Group-Project\node_modules\express\lib\view.js:135:8)
    at tryRender (F:\Uni\group-proj\research\Group-Project\node_modules\express\lib\application.js:640:10)
    at Function.render (F:\Uni\group-proj\research\Group-Project\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (F:\Uni\group-proj\research\Group-Project\node_modules\express\lib\response.js:1012:7)

**Comment by 0xMo** [comment]
this one is fixed, which could be closed
